layout_spectrum: 1
typography_spectrum: 0.6810036
color:
  saturation: 0.7526882
  lightness: 0.5860215
  brandStrength: 0.7545881
  brandColors:
    - '#F9F9F9'
    - '#303939'
    - '#909189'
    - '#F3E05C'
    - '#F2304B'
  rhythmicContrast: 0.5555556
name: Hellenrivera
