layout_spectrum: 0.5652475
typography_spectrum: 0.2379357
color:
  saturation: 0.4549061
  lightness: 0.06517395
  brandStrength: 0.7545881
  rhythmicContrast: 0.2319137
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Hellenrivera
